### ISSUE TITLE
Handle a response that does not begin with headers

### ISSUE THREAD

**Issue by dbohdan** [Elegant996/scgi-transport#1]
First, thanks for writing this module!  I think for some users (I know one) your work will finally put Caddy on par with Nginx.

Right now the module expects the response to begin with headers:
https://github.com/Elegant996/scgi-transport/blob/826f05d8f935add2fffd2a9d49895119813ccbf0/client.go#L172-L176
However, the SCGI spec does not mandate this.  [It says](https://python.ca/scgi/protocol.txt),
>The format of the response is not specified by this protocol.

It practice, SCGI server implementation like the [Wapp web framework](https://wapp.tcl-lang.org/) often respond with a status line first (like `HTTP/1.1 200 OK`), which makes them incompatible with the module.  Could you handle this case?

**Comment by Elegant996** [comment]
Added a check for raw status code if the status header is empty. Order will be: `Headers -> Raw -> Status 200`.

Thanks!
